package bgzipfuzz

// Edit if desired. Code generated by "fzgen -o ../../test/fuzz/fuzz_test.go .".

import (
	"testing"

	"github.com/retail-ai-inc/beanq/v3/helper/logger"
	"github.com/thepudds/fzgen/fuzzer"
)

// skipping Fuzz_ZapLogger_DPanic because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_Debug because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_Error because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_Fatal because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_Info because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_Panic because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_Warn because parameters include func, chan, or unsupported interface: []any

// skipping Fuzz_ZapLogger_With because parameters include func, chan, or unsupported interface: any

func Fuzz_NewWithConfig(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var cfg logger.ZapLoggerConfig
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&cfg)

		logger.NewWithConfig(cfg)
	})
}
