package bgzipfuzz

// Edit if desired. Code generated by "fzgen -o ../../test/fuzz/jwtfuzz_test.go .".

import (
	"testing"

	"github.com/retail-ai-inc/beanq/v3/helper/bjwt"
	"github.com/thepudds/fzgen/fuzzer"
)

func Fuzz_MakeHsToken(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var claims bjwt.Claim
		var key []byte
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&claims, &key)

		bjwt.MakeHsToken(claims, key)
	})
}

func Fuzz_ParseHsToken(f *testing.F) {
	f.Fuzz(func(t *testing.T, tokenStr string, key []byte) {
		bjwt.ParseHsToken(tokenStr, key)
	})
}
