linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - unused