FROM golang:1.22-alpine

# Proxy for China is enabled by default
RUN if [ "$USE_CHINA_PROXY" = "true" ]; then \
    go env -w GOPROXY=https://goproxy.cn,direct && \
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    else \
    go env -w GOPROXY=https://proxy.golang.org,direct; \
    fi

# The latest alpine images don't have some tools like (`git` and `bash`).
# Adding git, bash and openssh to the image
RUN apk update &&  \
    apk upgrade &&  \
    apk add --no-cache  \
    bash  \
    git  \
    openssh  \
    make  \
    autoconf  \
    gcc  \
    libc-dev  \
    sudo  \
    procps  \
    curl \
    jq

RUN mkdir -p /var/www/example

# Set the Current Working Directory inside the container
WORKDIR /var/www/example

# COPY . .

# RUN go mod tidy

ENTRYPOINT ["make","normal-consumer"]
